#!/usr/bin/env python3
"""Generate reference IF97 values from the iapws package for the C tests.

    PYTHONPATH=<dir with iapws> python3 tools/gen_if97_reference.py > tests/if97_reference.h
"""
import iapws
from iapws.iapws97 import _Region1, _Region2, _TSat_P
from iapws._iapws import _Viscosity, _ThCond

pts_r1 = [(3e6, 300.0), (80e6, 300.0), (3e6, 500.0), (15.5e6, 513.15), (14e6, 600.0),
          (1e6, 373.15), (5e3, 305.0), (16e6, 610.0)]
pts_r2 = [(3.5e3, 300.0), (3.5e3, 700.0), (14e6, 753.15), (14e6, 650.0), (1.5e6, 473.15),
          (0.1e6, 400.0), (5e3, 320.0), (16e6, 800.0)]
p_sat = [5e3, 0.1e6, 1e6, 5e6, 10e6, 14e6, 16e6]
ph = [(14e6, 1000e3), (14e6, 2000e3), (14e6, 3200e3), (5e3, 2300e3), (1.5e6, 2900e3),
      (15.5e6, 1030e3), (0.2e6, 500e3)]
ps = [(5e3, 7000.0), (1.5e6, 6300.0), (14e6, 6400.0), (14e6, 3000.0), (0.5e6, 6900.0)]

print("/* Generated by tools/gen_if97_reference.py from the iapws package. */")
print("static const double ref_r1[][6] = { /* p, T, v, h, s, cp */")
for p, T in pts_r1:
    r = _Region1(T, p / 1e6)
    print(f"    {{{p!r}, {T!r}, {float(r['v'])!r}, {float(r['h'])*1e3!r}, {float(r['s'])*1e3!r}, {float(r['cp'])*1e3!r}}},")
print("};")
print("static const double ref_r2[][6] = {")
for p, T in pts_r2:
    r = _Region2(T, p / 1e6)
    print(f"    {{{p!r}, {T!r}, {float(r['v'])!r}, {float(r['h'])*1e3!r}, {float(r['s'])*1e3!r}, {float(r['cp'])*1e3!r}}},")
print("};")
print("static const double ref_tsat[][2] = {")
for p in p_sat:
    print(f"    {{{p!r}, {_TSat_P(p/1e6)!r}}},")
print("};")
print("static const double ref_ph[][4] = { /* p, h, T, x */")
for p, h in ph:
    w = iapws.IAPWS97(P=p / 1e6, h=h / 1e3)
    print(f"    {{{p!r}, {h!r}, {float(w.T)!r}, {float(w.x)!r}}},")
print("};")
print("static const double ref_ps[][3] = { /* p, s, h */")
for p, s in ps:
    w = iapws.IAPWS97(P=p / 1e6, s=s / 1e3)
    print(f"    {{{p!r}, {s!r}, {float(w.h)*1e3!r}}},")
print("};")
print("static const double ref_tr[][4] = { /* rho, T, mu, k */")
for rho, T in [(998.0, 298.15), (800.0, 500.0), (650.0, 600.0), (50.0, 700.0), (5.0, 450.0)]:
    print(f"    {{{rho!r}, {T!r}, {float(_Viscosity(rho, T))!r}, {float(_ThCond(rho, T))!r}}},")
print("};")
