#!/usr/bin/env python3
"""Emit the IAPWS-IF97 region 1/2 coefficient tables as a C header.

The numbers come from the reference `iapws` Python package, so the C
implementation never contains hand-typed coefficients.

    PYTHONPATH=<dir with iapws> python3 tools/gen_if97_coeffs.py > src/core/rm_if97_coeffs.h
"""
import iapws._iapws97Constants as C


def arr(name, ctype, values, fmt):
    body = ",\n    ".join(", ".join(fmt(v) for v in values[i:i + 4])
                          for i in range(0, len(values), 4))
    return f"static const {ctype} {name}[{len(values)}] = {{\n    {body}\n}};\n"


def f(v):
    return repr(float(v))


def i(v):
    return str(int(v))


out = ["/* Generated by tools/gen_if97_coeffs.py from the iapws package. Do not edit. */",
       "#ifndef RM_IF97_COEFFS_H", "#define RM_IF97_COEFFS_H", ""]
out.append(arr("if97_r1_I", "int", list(C.Region1_Li), i))
out.append(arr("if97_r1_J", "int", list(C.Region1_Lj), i))
out.append(arr("if97_r1_n", "double", list(C.Region1_n), f))
out.append(arr("if97_r2_J0", "int", list(C.Region2_cp0_Jo), i))
out.append(arr("if97_r2_n0", "double", list(C.Region2_cp0_no), f))
out.append(arr("if97_r2_I", "int", list(C.Region2_Li), i))
out.append(arr("if97_r2_J", "int", list(C.Region2_Lj), i))
out.append(arr("if97_r2_n", "double", list(C.Region2_n), f))
out.append("#endif")
print("\n".join(out))
